[WIP] Portlet-PO for Build Statistics and simple tests
darenegade/acceptance-test-harness pull request #15
Opened 2017-04-23 18:18 UTC by darenegade

2017-04-27 12:53 UTC, darenegade commented
@uhafner Bitte einmal drüber schauen. Das ist der erste PR mit Tests für ein Poltet

2017-04-28 18:05 UTC, uhafner requested changes

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +  public enum Jobtype{
[Coding style:](https://github.com/uhafner/codingstyle/blob/master/doc/Formatierung.md) whitespace before a brace.

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +      row =r;
ws

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +   * Get the Buildstatistics table as {@link WebElement}
Active: gets

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +  public WebElement getTable(){
Is public required or is everything accessible via getters?

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +   * @return int
the number of builds

2017-04-28 18:05 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +   * @return int
the percentage

2017-04-28 18:05 UTC, uhafner commented on src/test/java/plugins/DashboardViewPluginTest.java
> +        DashboardView v = jenkins.views.create(DashboardView.class, "dashboard");
Create a new 1-arg method in ViewsMixIn that uses createRandomName()

2017-04-28 18:05 UTC, uhafner commented on src/test/java/plugins/DashboardViewPluginTest.java
> +
In order to reduce the duplication you can extract 55-61 into a method, then the code looks like this:
```
        DashboardView v = createDashboard();
        BuildStatisticsPortlet stats = v.getBottomPortlet(BuildStatisticsPortlet.class);
```

2017-05-01 15:39 UTC, darenegade commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +  public WebElement getTable(){
I just use the public `find` method here, so i don't see a reason to block the accessibility.

2017-05-03 09:25 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +    public int getNumberOfBuilds(Jobtype type) {
Maybe I'm somewhat pedantic ;-) Here is an example of a JavaDoc following my coding style: 
- Active voice
- First sentence ends with a point
- Return value is named 
- Uppercase only for actual sentences

```
/**
 * Gets the number of builds of a specific {@link Jobtype}.
 *
 * @param type type of job
 * @return number of builds
 */
```

2017-05-03 09:25 UTC, uhafner commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +    public enum Jobtype {
JobType CamelCase

2017-05-03 09:25 UTC, uhafner approved these changes

2017-05-03 17:35 UTC, darenegade commented on src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java
> +    public int getNumberOfBuilds(Jobtype type) {
Yes, I see. I just followed the overall javadoc coding style of this project. 😄
(Just kidding - I will change that)

2017-05-04 12:36 UTC, merged