Fixed color tests
darenegade/acceptance-test-harness pull request #27
Opened 2017-06-21 16:28 UTC by darenegade

closes #26 

@peter-mueller @maximilian-zollbrecht

2017-06-21 16:29 UTC, darenegade commented
Bitte testen, ob es bei euch geht

2017-06-22 09:01 UTC, maximilian-zollbrecht requested changes
Der failure- und success-Test schlägt bei mir immer noch fehl. Der failureAndSuccess funktioniert.

Ich habe bei den beiden die fehlschlagen 2 Farben statt einer:
Die 2te Farbe ist geradeso über den 5%. Eventuell die Grenze leicht anheben, oder die Ausnahmen erweitern.
![bildschirmfoto vom 2017-06-22 10-54-19](https://user-images.githubusercontent.com/13729948/27425705-990c9f28-5739-11e7-8cb4-7be1472b8fc2.png)

2017-06-22 09:26 UTC, darenegade commented
@maximilian-zollbrecht Jetzt sollte es gehen.

2017-06-22 09:41 UTC, maximilian-zollbrecht approved these changes

2017-06-22 09:41 UTC, merged